### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by luizfonseca**
Add Docker instructions

### CODE REVIEW

**Comment by luizfonseca** [comment]
@harshbanthiya 
@uchiha21itachi 
@ronalson 
@e-pelon 

I added instructions on how to install and use the project with Docker. Take a look on the README and make sure it's working! :D

**Comment by e-pelon** [comment]
Done!

Sent from my iPhone, please excuse brevity and typos.
Direct Line: 707 301 6527

**Comment by harshbanthiya** [comment]
cant initialize postgres 
as soon as I put "docker-compose -d postgres "    

it doesnt recognize the command  I guess   
is it the correct command ?

this is what I got ... 

➜  slive git:(master) ✗ docker-compose -d postgres                      [2.3.4]
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file (default: docker-compose.yml)
  -p, --project-name NAME     Specify an alternate project name (default: directory name)
  --verbose                   Show more output
  -v, --version               Print version and exit
  -H, --host HOST             Daemon socket to connect to

  --tls                       Use TLS; implied by --tlsverify
  --tlscacert CA_PATH         Trust certs signed only by this CA
  --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
  --tlskey TLS_KEY_PATH       Path to TLS key file
  --tlsverify                 Use TLS and verify the remote
  --skip-hostname-check       Don't check the daemon's hostname against the name specified
                              in the client certificate (for example if your docker host
                              is an IP address)
  --project-directory PATH    Specify an alternate working directory
                              (default: the path of the Compose file)

Commands:
  build              Build or rebuild services
  bundle             Generate a Docker bundle from the Compose file
  config             Validate and view the Compose file
  create             Create services
  down               Stop and remove containers, networks, images, and volumes
  events             Receive real time events from containers
  exec               Execute a command in a running container
  help               Get help on a command
  images             List images
  kill               Kill containers
  logs               View output from containers
  pause              Pause services
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pull service images
  push               Push service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  top                Display the running processes
  unpause            Unpause services
  up                 Create and start containers
  version            Show the Docker-Compose version information

**Comment by harshbanthiya** [comment]
I think  I dont have postgres gem but do I install postgres gem for ruby ? or Python ?

**Comment by harshbanthiya** [comment]
update: I have postgresql gem 
still not working
still getting the same result on running the command

**Comment by luizfonseca** [comment]
The command Is "docker-compose *run*" 

And Docker doesn't need you to install anything. It doesn't rely on your system to have installations, he is basically creating a virtual Postgres for you. Even if you formatted your computer and you had nothing on it except Docker, it would work! Virtual machinessssss



--
Luiz Fonseca 
+55 21 997137471

**Comment by e-pelon** [comment]
Badass

**Pull request merged**
